apiVersion: v1
kind: Service
metadata:
  name: geobeefront
  labels:
    app: geobeefront
spec:
  type: LoadBalancer
  ports:
    - port: 3000       # The port that the service listens on
      targetPort: 3000 # The port that the container listens on
  selector:
    app: geobeefront   # The label that selects the pod
