apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: postgis/postgis:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgis-secret
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgis-secret
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgis-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgis-service
spec:
  selector: 
    app: postgis
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
