apiVersion: v1
kind: Secret
metadata:
  name: postgis-secret
type: Opaque
data:
  DB_CONNECTION: cGdzcWw=        # pgsql
  DB_USERNAME: cG9zdGdyZXM=      # postgres
  DB_PASSWORD: ZWRv              # edo
  DB_NAME: dGFuZ2VyYW5nYWRt      # tangerangadm
  DB_PORT: NTQzMg==              # 5432


  # if using MySQL
  # DB_CONNECTION: "bXlzcWw=" # mysql
  # DB_NAME: "ZXhlcmNpc2UtYXBw"
  # DB_HOST: "cHJveHlzcWwucHJveHlzcWw=" # proxysql.proxysql
  # DB_USERNAME: "WVdSdGFXND0=" # admin
  # DB_PASSWORD: "c3VwM3JzM2NyM3Q="
  # DB_PORT: "NjAzMw==" #6033